services:
  app:
    build:
      context: .
      args:
        COMMIT_HASH: ${COMMIT_HASH}  # Passing COMMIT_HASH as an argument
    volumes:
      - ./afflicted-events.txt:/usr/src/app/afflicted-events.txt  # Dynamic file
      - ./players.db:/usr/src/app/players.db  # Database file
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    networks:
      - adcom-sites
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    restart: unless-stopped

networks:
  adcom-sites:
    name: adcom-sites
    external: true
